title: 沼泽领主的居所
story: 欢迎牌已经风化，几乎无法辨认。在这里，沼泽边缘，一栋房屋正逐渐荒废。邻近城镇的人们看起来很糟糕。镇民们怀念着过去的日子，那段时光已经久远得如同传说。“老德雷伦被驱逐出奥本达后，试图躲藏在那座小山上。那是大家见过的最好的草药师。据说他为了证明自己能治愈各种疾病，故意让自己感染了这些疾病。但后来，他无法逆转这些效果。于是他与某个生物达成协议，那生物为他制造了一台维持生命的机器。最终，有人举报了他，把他和他的机器赶进了毒沼。这里的植物变得很病态，镇上的人们也一样。他在那座小山上留了一堆药品，但这里的人们从未能利用起来。”
choices:
  - description: 搜索温室。好多药水和草药……
    action: 每个Gearloc必须选择并掷出6个攻击/防御骰子，然后可以重新掷其中最多3个。在最终掷出后，队伍可以在每人服用药水之前交换结果（1对1）。如果得到下面配方，那个Gearloc将在下一次战斗中开始时带有一个毒药2标记。1. 混合治疗药：获得2Buff HP（攻1，攻1，防1，防1，骨头）。2. 混合训练药：获得1个训练点数（攻1，防2，防2，防1，骨头）。3. 混合解毒药：这个Gearlock在所有战斗中免疫毒（攻2，防2，骨头，骨头，骨头，骨头）。4. 混合隐形药：这个Gearlock下次战斗中获得先发制人（攻1，攻1，防2，防1，防1，防1）。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
remark:
progress: [1]
card_type: tyrant