title: 戴洛尔的满月
story: 连续五周的满月，今天并不是猎杀狼人的最佳时机。如果面前的哥布林商人所说属实，这个月亮会给予穆尔梅什额外的力量，所以最好提前计划。他讲述了在石拳附近的一个洞穴，并指向小路尽头的一个敌对哥布林商人。“穆尔梅什喜欢哥布林肉。用他来引诱穆尔梅什进入洞穴，避开月光。我现在就感谢你；你以后可以再谢我。”紧张的笑声在空气中回荡，狡猾的哥布林恶狠狠地磨着他的匕首。
choices:
  - description: 我们不与商人做交易！哥布林商人大怒并且叫了他的经理。
    action: BQ：反派点数，增加哥布林商人（20点）。Gearloc有突袭。Gearloc可以支付（丢弃）1个战利品来说服哥布林商人跳过自己的回合。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。队伍获取1个宝藏战利品。获取1点进度点。
  - description: 问候，敌对商人。我在狼人巢穴附近有一个很好的新货源！
    action: 放置哥布林商人（20点）并将此卡放入一个Gearloc的战利品区域（视为重型战利品）。持久效果：在与穆尔梅什的暴君战斗中，如果哥布林商人在一个Gearloc的战利品区域，将商人喂给穆尔梅什以引诱他走出月光。然后穆尔梅什只有在HP为2或更少时才会撤退。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: tyrant