title: 你被篡位了
story: 诺姆本人正沿着这条路奔来，看似全力奔跑。他那强壮的身躯让地面震动。他似乎准备在此结束这段旅程，但却毫无意外地冲了过去。他的雷霆棒砸向了另一只从后方冲来的更大的巨魔的额头。这场面就像巨人的选举，没有投票箱，但Gearlocs可以用箭和剑来投票。
choices:
  - description: 去投票！
    action: BQ：巨魔篡位者（Troll Usurper 20点），加入诺姆（暴君）。在这场战斗中，巨魔篡位者和诺姆只会互相攻击。一旦诺姆或巨人篡位者被击败，战斗结束。如果巨魔篡位者击败了诺姆，暴君战斗变成与篡位者战斗。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1个进度点。
  - description: 中断竞选活动，我们就在这里，现在结束这一切。
    action: BQ：反派点数，加入巨魔篡位者（Troll Usurper 20点），加入诺姆（暴君）。如果所有反派被击败（包括诺姆），游戏成功。
    rewards:
remark:
progress: [1, 0]
card_type: tyrant