title: 厚皮之患
story: 站在那里的诺姆，身形如同一个Gearlock小屋，就在道路中间。诺姆，这个巨魔酋长和他的手下显然不怕他们巢穴的安全。他们渴望鲜血，而这场战斗来得太早了。对诺姆有利，对这一方的战线却不利。在几乎没有时间准备的情况下，必须想办法拖延这场遭遇战！也许以暴制暴会让诺姆退缩。如果不行的话，今天诺姆的雷霆锤声将响彻戴洛尔。
choices:
  - description: 这家伙似乎并不可怕。
    action: BQ：反派点数。队伍人数为1-2：在反派队列中加入两个1点反派。队伍人数为3-4：在反派队列中加入两个5点反派。将诺姆放置在反派队列的顶部。诺姆将在第3回合结束时或其生命值降至5点或以下时立即离开战斗。其他反派将继续完成战斗。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1个进度点。
  - description: 慢慢撤退… 好吧，赶紧撤！
    action: 诺姆追逐队伍整整一天一夜。你队伍中的每个Gearlock失去2点生命值并且必须跳过恢复阶段。将这张遭遇卡洗回遭遇卡组。
    rewards: 每个Gearlock获得1个技能点。
remark:
progress: [1, 0]
card_type: tyrant