title: 我们有个哥布林难题
story: 到处都是哥布林。这些戴洛尔的“蝗虫”似乎数量在惊人地增长。无论砍倒多少，总有其他哥布林出现填补位置。看起来根本无法削减他们的数量。筋疲力尽且进度落后，每浪费一分钟在这些讨厌的家伙身上，都给了哥布林王集结并派遣援军的时间。显然，必须找到一种不同的方法来解决这个问题。这场瘟疫必须从源头上根除。不幸的现实是，最直接的方法意味着……呃……更多的哥布林。
choices:
  - description: 继续前进！哥布林王即将触手可及！
    action: BQ：反派点数。队伍人数为1-2：在反派队列顶部添加一个1点哥布林类型反派。队伍人数为3-4：在反派队列顶部添加一个5点哥布林类型反派。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark: 持续效果：将以下效果应用于每次遇到包含“BQ：反派点数”的未来战斗中：将最后一个被击败的哥布林类型反派添加到反派队列顶部。
progress: [1]
card_type: tyrant