title: 大厅与宝珠
story: 这美景令人屏息。这种建筑的华丽和精美装饰超越了任何Gearloc的最狂野梦想。大理石柱上雕刻着华丽的象牙装饰，支撑着金箔屋顶。黑曜石地板让Gearloc的靴子显得格外破旧。房间中央，一座坚固的玻璃基座托着一个微微脉动的宝珠。死寂般的宁静，大厅中既散发着恐惧，又展现着美丽和力量。宝珠似乎在观察房间中的一切，虽然它既不移动也不发出声音。摧毁如此美丽的东西似乎是一种罪行，但它具备了根德里克斯危险而强大神器的所有特征。
choices:
  - description: 击倒那根柱子！
    action: BQ：反派点数。当反派进入战斗垫后，放置Gearloc人数乘3点生命值到一个堆叠（宝珠）中，并将其放置在一个开放的反派远程位置。每轮结束时，宝珠对未与其相邻的敌方单位造成1点伤害。队伍将宝珠视为敌方单位。Gearlocs必须摧毁宝珠和反派才能成功。成功后，此卡片也变为持久Buff。暴君战斗期间创建的任何宝珠将从3点生命值开始，而不是4点。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1]
card_type: tyrant