title: 失控
story: 从这个高处俯瞰山谷，可以看到两小队兽人。他们分别从西北和东北出发，在唯一的山路前方建立营地。他们的数量在不断增加，而且营地的位置看起来是经过精心安排的。是侦察兵通知了他们，还是那些一天前快速通过的商人？不管是哪种情况，他们显然已经准备好战斗。这将是一场艰难的战斗。
choices:
  - description: 无论发生什么，这都会很痛苦。
    action: BQ：反派点数。使用尽可能多的兽人类型反派（来自活动或已击败堆叠）创建反派队列。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark: 在战斗的前3个回合中，任何被击败的兽人都将被重新加入到BQ的底部。
progress: [1]
card_type: tyrant