title: 马罗的内战
story: 马罗因其军事战术而闻名戴洛尔，但他不愿离开自己的据点，这显然导致了他的指挥失效。各派系只追随自己的行动，并巩固他们在该地区的地位。大量的军队在关口的两侧形成，他们看起来要相互对峙！来自戴洛尔沼泽的生物浪潮正与显然是狗头人军队精英的对手一决雌雄。这场战斗正在发生，没有退路。是时候选择一个阵营，否则马罗阵营中的分裂将是这次冒险的终结！
choices:
  - description: 选择狗头人。打倒沼泽生物！
    action: BQ：反派点数。使用正在使用或已击败的沼泽类型反派创建反派队列。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
  - description: 选择沼泽生物。让我们消灭这些蜥蜴！
    action: BQ：反派点数。使用正在使用或已击败堆叠的鳞片怪类型反派创建反派队列。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
remark: 今天的战斗只会与一种类型的怪物战斗。如果成功，这种类型的怪物将会在全部战斗中被移除。谨慎选择。
progress: [1, 1]
card_type: tyrant