title: 暗影群狼
story: “回到奥本达把它烧毁。你根本不知道你在招惹什么。”达斯特从阴影中显现出来，随意地靠在一棵明显已经历经风霜的Zelfey树上。她脸上的伤疤在月光下闪闪发光。怎么可能一个伤疤同时看起来既新鲜又年代久远？在树干之间，可以看到黄澄澄的巨狼眼睛。“我不想杀你，但我会不惜一切代价阻止你。”她没有再说一句话，便悠然返回阴影中。她走了。但她的狼群还在。
choices:
  - description: 别想逃跑！
    action: BQ：反派点数。1-2人队伍：在反派队列顶部添加一个5点兽类反派。3-4人队伍：在反派队列顶部添加两个5点兽类反派。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 它们有可能是友善的吗？
    action: 你伸出手让最大的狼嗅你：选择1个Gearlock掷一个D6。1-2：狼咬住你的手并带走它。永久减少1个Gearlock的生命值骰子3点（不能低于起始生命值）。3-6：狼被你的大胆震慑住，带着狼群离开。无论结果如何，此遭遇都算成功。
    rewards: 每个Gearlock获得2个技能点。获取1点进度点。
remark:
progress: [1,1]
card_type: tyrant