title: 援助包裹
story: 在戴洛尔的路中间发现箱子时，总要保持警惕。这三个箱子看起来装有贵重物资。很可能是陷阱。本能要求先侦察周围环境，然后再回到箱子前面。小心地打开前两个箱子，令人惊讶地发现里面真的有一些有价值的物品。然而，第三个箱子有着无法掩盖的哥布林气味，从粗糙的木材中散发出来。哥布林喜欢危险的恶作剧，而这可能是其中之一，这一事实在箱盖上的涂料被揭示时完全得到了证实，上面写着：“来自哥布林王的问候”。
choices:
  - description: 我拒绝有哥布林头的臭箱子。忽略那个箱子！决定趁机离开。
    action: BQ：反派点数。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
  - description: 尝试拆除！
    action: BQ：反派点数。每个Gearlock必须命名一个锁类型（Lever, Trip, or Force）并通过开锁尝试（达到该类型的3）。如果成功，箱子被拆除，里面的炸弹可以在战斗开始时立即用来摧毁哥布林王的“王座”。（视为战利品，永久）。如果失败，战斗开始前，您的每个Gearlock成员失去2点生命值。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
remark:
progress: [1,1]
card_type: tyrant