title: Gearlock的气味
story: 你就算不是巡逻者也能感觉到自己被跟踪了。当你的胃本能地收紧，耳朵上的毛发竖起时，可能有双眼睛在注视着你。能做什么呢？在这种情况下，什么都不能做。试图揭开这个追踪者会浪费太多时间。然而，几个小时后，偏执开始侵袭。每一刻都感觉有更多的眼睛在注视着。黑影在树间进出，总是隐藏着，但就在眼角出现。他们在等待什么？
choices:
  - description: 又一阵胃部抽搐…这种感觉越来越频繁。
    action: 在你的未使用怪物堆中搜索第一个野兽类型的反派并将其放在暴君卡上，这将被添加到暴君战斗中。队伍人数1-2： 搜索1点反派。队伍人数3-4： 搜索5点反派。如果没有找到正确的反派，搜索你已经击败的反派。为今天抽取另一个遭遇卡，并将此卡重新洗入你的遭遇牌组。
    rewards:
remark:
progress: [0]
card_type: tyrant