title: 迷雾之中
story: 迷雾令人窒息。视野不过几英尺，很容易想象到处都是达斯特的脸。那道疤，那把匕首。“委员会不可信，你知道吗。”话语轻如耳语，但却清晰响亮。迷雾。窒息。视野全无。她就在这里，但又无处可寻。也许是雾在捉弄眼睛和耳朵？“他们是懦夫，否则他们会亲自来找我。就像第一次那样。”几秒钟过去，雾散了。闯入狼窝通常是不明智的。
choices:
  - description: 谁有剩下的沼泽肉？
    action: BQ：反派点数。用活跃或已击败的野兽型反派创建反派队列（尽可能多，然后再使用其他类型）。战斗设置期间，将队员只放置在Gearloc的近战位置。然后，将反派只放置在Gearloc的远程位置（设置完毕后，恢复正常的BQ位置规则）。反派有先发制人。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。
remark:
progress: [1]
card_type: tyrant