title: 离开奥本达
story: 离黎明还有12小时，送别仪式无疑会改变每个幸存Gearloc的命运（很可能还包括戴洛尔的每一个生命）。武器和补给品已经准备就绪，但夜晚尚早，肾上腺素在血管中奔腾。显然，今晚不会有任何睡意。在黑暗的小巷里，肯定有一些阴暗的小贩准备进行战利品交易。再者，临阵磨枪的训练到天亮时也可能带来不错的回报。那么，做什么呢……做什么呢……？
choices:
  - description: 挤出最后的时间进行自我提升。
    action:
    rewards: 每个Gearlock获得2个技能点。获取1点进度点。
  - description: 搜查一个阴暗的小贩！
    action:
    rewards: 每个Gearloc可以抽取2个战利品，并选择1个保留。每个Gearlock获得1个技能点。获取1点进度点。
remark:
progress: [1,1]