title: 偶遇
story: 当你听到荒野动物园的声音、各种战争的喊声，甚至同伴的闲聊声逐渐变成无法分辨的噪音时，你就知道你已经疲惫不堪了。所以，当我们在经过一天的旅途，每一个转弯都充满危险时，突然听到空气中飘来的音乐声，从前方的空地传来时，可以想象我们有多么惊讶。在检查自己是否出现妄想症状并确认我们神志清醒后，我们加快了脚步，一顿丰盛的晚餐和友好的交易的诱惑实在难以忽视。幸运的是，与之前的一些不愉快经历不同，这次音乐没有让我们失望，我们遇到了一群提供友谊……和挑战的商人。
choices:
  - description: 撬锁挑战！你开锁，你保留！
    action: 浏览宝藏战利品牌堆，直到找到一个至少有一个5难度锁的宝藏战利品。每个Gearloc都有一次撬锁尝试。一个Gearloc打开的锁为下一个Gearloc保持打开状态。队伍必须解锁宝藏战利品才能成功完成此遭遇。
    rewards: 队伍获得1个宝藏战利品。每个Gearloc可以抽取1个战利品。
  - description: 危险飞镖......再次来袭。
    action: 每个Gearloc必须参加危险飞镖挑战。至少一个Gearloc获胜才能使队伍取得进展。每个获胜者还会获得1个战利品。
    rewards: 每个获胜者还会获得1个战利品。
remark:
progress: 1