name: 德雷伦·白面
id: drellen
description: 很多年前，德雷伦因某些没人能（或愿意）回忆的原因被驱逐出奥本达，被放逐到毒沼。然而，他并没有死去，而是存活了下来。长期在沼泽中的生活让他的脸部扭曲且满是伤疤，他只剩皮包骨头。然而，不知为何，他在沼泽中茁壮成长。
min_progress: 6
max_days: 10
game_length: 2/6
battle_title: 沼泽之战
creatures: 沼泽怪，地精，野兽
battle_mechanism:
- 将德雷伦放在1号路径。抽取沼泽类型的反派，并放置在2号和3号路径。1-2人队伍：两个1点沼泽类型反派。3-4人队伍：两个5点沼泽类型反派。
- BQ：反派点数（1人队伍忽略此项）。
- 在这场战斗中，每次移动位置需要2点敏捷而不是1点。
tyrant_skills:
- 沼泽之王：如果战斗垫上有任何沼泽类型的反派，德雷伦不会失去生命值。毒素对德雷伦无效。
tyrant_die:
- 毒素增强：将德雷伦目标上的任何现有毒素效果骰子设为3。
- 毒素2：目标中毒2点。将效果骰子放在目标上。