name: 达斯特
id: duster
description: 刚刚掌权不久，达斯特在处理伊本事务时似乎有自己的计划。在悄悄暗杀了伊本哈特的前任统治者并将其追随者收为己用之后，她已经积聚了不少追随者。达斯特一直在寻找着什么，始终是个谜。
min_progress: 10
max_days: 13
game_length: 6/6
battle_title: 最终冲突
creatures: 沼泽怪，地精，野兽，巨魔，鳞片怪，兽人
battle_mechanism:
- BQ：反派数量等于队伍规模。1-2人队伍：使用1点反派。3-4人队伍：使用5点反派。
- 将达斯特添加到BQ顶部。达斯特将在速度Meter上占据顶部位置。
tyrant_skills:
- 遮蔽：达斯特只能被相邻的单位当做目标。
- 限制：达斯特的目标立即从他们的Gearloc垫上移除一个属性骰子，在这场战斗的剩余时间内有效。如果移除了生命值或防御属性骰子，调整生命值/当前防御以反映新的最大值。
- 隐匿：达斯特在她的下一回合前不能成为目标。
tyrant_die:
- 斗篷与匕首：如果战斗垫上有2个或更多Gearloc，暂时将速度Meter上的下一个Gearloc从战斗垫上移除，并将达斯特放置在他们的战斗垫位置上。当Gearloc被击倒时，下一个Gearloc将在回合结束后在战斗垫上选择起始位置并在速度Meter上占据顶部位置！
- 达斯特的匕首：在达斯特本回合造成伤害的任何目标(一个)上放置一个出血效果骰子