name: 根德里克斯
id: gendricks
description: 为了在战斗中占得优势，根德里克斯随时准备焚烧自己的同类。他在整个地区被公认为一个无情而危险的领袖。据说他的巢穴中有神秘的柱子，由他的法杖控制，但没有生物活得足够久来证实这个传说。
min_progress: 8
max_days: 10
game_length: 3/6
battle_title: 天平之像
creatures: 沼泽怪，巨魔，鳞片怪，兽人
battle_mechanism:
- BQ：反派点数（1人队伍忽略此项）。在BQ顶部添加一个1点狗头人反派。将根德里克斯添加到BQ顶部。
tyrant_skills:
- 耐久：任何回合根德里克斯受到伤害（包括真实伤害），总伤害减至1点。
- 限制：根德里克斯的目标立即从他们的Gearloc垫上移除一个属性骰子，在这场战斗的剩余时间内有效。如果移除了生命值或防御属性骰子，调整生命值/当前防御以反映新的最大值。
- 根德里克斯只有在球体未激活时才能掷暴君骰子。
tyrant_die:
- 活跃球体：将这个骰子和4点生命值放置在反派路径（骰子结果编号）的远程位置。如果该位置已被占用，则尝试同一路径中的下一个位置，依此类推。如果该路径的所有4个位置都被占满，球体未被激活。当球体在战斗垫上时，每当一个Gearloc掷出一个骷髅，对那个Gearloc造成1点伤害。团队将球体视为敌对单位。
- 焦炭曼德：根德里克斯用火球攻击最弱的狗头人反派，造成1点伤害。那个狗头人立即移动到最近的敌对单位旁边，并对其造成2点伤害。