name: 哥布林国王
id: goblin_king
description: 哥布林国王王本性难测，通过纯粹的恐怖手段紧紧控制着战火尖塔地区。他的追随者极其忠诚，没人敢越雷池一步，生怕背后中了一颗炸弹。
min_progress: 8
max_days: 12
game_length: 4/6
battle_title: 王座之战
creatures: 沼泽怪，巨魔，野兽，巨魔
battle_mechanism:
- 在1号路径的远程位置设置一个王座，使用1号路径标记，并给予3点生命值。将哥布林国王（及其生命值）放在王座上。
- BQ：反派点数（1人队伍忽略此项）。
- 王座只会受到相邻敌方单位的伤害，并且哥布林国王在王座摧毁之前不能受到伤害。哥布林国王的防御力不适用于王座。哥布林国王不能对自己造成伤害。
tyrant_skills:
- 轰炸：将所有齿轮族炸至离地精王最远的位置（在造成伤害之前发生）。
- 爆炸：地精王造成的任何伤害也会对其目标相邻的单位造成一半伤害（向下取整）。
tyrant_die:
- 呼叫支援：在BQ底部添加一个反派单位。BQ：1-2人队伍：1点反派。3-4人队伍：5点反派。
- 粗心炸弹3：对最强的反派及所有相邻单位造成3点伤害。