name: 马罗
id: marrow
description: 马罗——在戴洛尔提到这个名字，足以让任何人毛骨悚然。这名兽人从未输过一场战斗，并且是一位大师级战略家。他还轻松挥舞着一把相当于一个Gearloc大小的斧头。马罗知道如何在战斗中等待时机，并且毫不犹豫地利用他的众多追随者来确保胜利。
min_progress: 10
max_days: 12
game_length: 5/6
battle_title: 烈焰战斧
creatures: 沼泽怪，地精，鳞片怪，兽人
battle_mechanism:
- 将马罗放置在3号路径的远程位置。
- BQ：反派点数（1人队伍忽略此项）。
tyrant_skills:
- 掠夺：每增加一个在战斗垫上的兽人类型反派，马罗获得一个额外的攻击骰子。
- 召唤兽人：如果马罗掷出一个骷髅，添加一个1点兽人类型反派到BQ顶部。如果掷出两个或更多骷髅，改为添加一个5点兽人类型反派到BQ顶部。如果没有可用的兽人，重复使用已击败的兽人。
tyrant_die:
- 裂骨斧：马罗的攻击在本回合造成真实伤害。
- 血怒：移除马罗身上的任何效果。在马罗回合结束时，他向3号路径的远程位置移动2个位置，并恢复3点生命值。