name: 穆尔梅什
description: 曾经是人类，现在是狼人，穆尔梅什对他曾经的身份有着无法满足的渴望。他知道再也无法回头。这种渴望激起对任何阻挡他复仇之路的非伊本戴洛尔人类的愤怒。
min_days: 6
max_days: 9
game_length: 2/6
battle_title: 午夜战争
creatures: 沼泽怪，野兽，鳞片怪
battle_mechanism:
- BQ：反派点数（1人队伍忽略此项）。将这张卡上的所有反派放置在BQ顶部。将穆尔梅什添加到BQ底部。
tyrant_skills:
- 狂暴2：如果穆尔梅什的攻击骰击中（没有掷出骷髅），再次掷出没有骷髅的攻击骰，并将两次掷骰的总伤害相加。
- 撤退：如果穆尔梅什以3点或更少的生命值开始他的回合，他将被移出战斗垫并进入BQ顶部。当他重新加入战斗时，穆尔梅什的生命值将恢复。出血或中毒等状态效果可以在穆尔梅什的生命值恢复后施加。
- 遮蔽：穆尔梅什只能被相邻的单位当做目标。
tyrant_die:
- 银色皮肤：穆尔梅什在下一回合前不会受到攻击骰的伤害。
- 嚎叫：所有友方单位立即在速度Meter上提升1个位置（不能超过穆尔梅什的位置）。