name: 诺姆
description: 巨魔这种生物不怎么聪明。作为页拳地区的巨魔首领，诺姆也不例外。然而，从来没有人觉得有必要向诺姆指出这一点，原因显而易见，比如巨大的体型差异和雷霆棍。也可能是因为诺姆喜欢把激怒他的人关在笼中，然后在笼中一对一地对抗他的猎物。
min_progress: 6
max_days: 8
game_length: 1/6
battle_title: 与诺姆斗殴
creatures: 巨魔，鳞片怪，兽人
battle_mechanism:
- BQ：反派点数（1人队伍忽略此项）。将诺姆添加到BQ底部。
- 战斗垫上一次只能有一个Gearloc！Gearlocs决定谁先进入战斗垫，其余在一旁等待。当Gearloc被击倒时，下一个Gearloc将在回合结束后选择一个战斗垫的起始位置和并把自己的速度骰放在速度Meter首位！
tyrant_skills:
- 厚皮3：诺姆每回合忽略他将受到的前3点伤害（不忽略真实伤害）。
- 恢复1：诺姆在其行动开始前获得1点生命值（最高到最大值）。
tyrant_die:
- 吞噬：在造成伤害之前，移除目标的所有防御骰子。
- 雷霆棍：诺姆攻击后，将目标击退至战斗垫上离其当前位置最远的位置，并造成1点真实伤害。