title: 跨越西布朗河
story: 西布朗河，这条闪闪发光的贸易之脉贯穿戴洛尔全境，在前方的日光下顽皮地闪烁，诱人前行。但由于这里的桥梁稀少，这个渡口显然是敌方侦察兵和陷阱的好地方。这次重要的旅程只有两个选择。将耳朵藏起来试图混入其中，虽然风险大，但效率高。或者傍晚乘船，虽然被发现的几率较小，但需要与莫尔诺尔做交易——一个有着自己一套……缺点的贸易集团。
choices:
  - description: 藏起耳朵，像普通人一样行走。
    action: 队伍中的每个Gearloc掷一个D6。任意Gearlock掷出1-2：你的队伍被发现。找到你卡组中的第一个暴君遭遇卡并将其置于顶端。将剩余的卡洗牌并放在下面。无论结果如何，遭遇成功。
    rewards: 每个Gearlock获得1个技能点。获取额外1点进度点。
  - description: 雇佣莫尔诺尔。
    action: 莫尔诺尔出奇地好合作。他们不仅在黑暗掩护下将我们安全送到河东岸，还赠送了一个宝藏战利品“礼物”。也许我们的成功对生意有好处？将特别遭遇——莫尔诺尔商人洗入你的遭遇卡组。
    rewards: 每个Gearlock抽取1个宝藏战利品。
remark:
progress: [2, 1]
card_type: day3