title: 乌晶门
story: 这竟然是真的——传说中的乌晶门！它的存在一直是月光独白和炉边故事的主题。而现在，它就在这里！是时候看看宝藏也是否是真的了！地图显示按顺序按下每块石头，从最小到最大，来打开这扇门。检查！现在，每块隧道石也必须以同样的方式踩踏。检查！最后，按顺序点燃火炬……感觉自己应该戴着帽子，拿着鞭子！哇！金光刺眼，但Gearlocs对黄金不感兴趣。这里有用的东西吗？
choices:
  - description: “嗯……我能闻到这里的宝藏战利品的味道！”
    action: 每个Gearloc可以抽取2张宝藏战利品卡。保留1张，弃掉另一张。每个Gearloc可以立即进行一次开锁尝试。
    rewards: 每个Gearlock获得1个技能点。每个Gearlock抽取1个宝藏战利品。
  - description: “作战室！？这才对味！”
    action: 在这里进行攻击和防御属性训练尝试将始终无视所有骷髅。
    rewards: 每个Gearlock获得2个技能点。每个Gearlock抽取1个战利品。
remark:
progress: [0,0]
card_type: special