title: 狩猎猎人
story: 这显然不是巧合。每次一个强大的反派被击倒，总会有更大更强的敌人紧随其后。似乎每次你惹到小家伙，爸爸或妈妈总会赶来帮忙。这种情况令人疲惫不堪。在某个时刻，继续逃跑不如直接面对整个家族更有意义。这是一个令人恐惧的前景！它们全都大得离谱！
choices:
  - description: 蹲下掩护，抓起能拿的东西，跑！
    action: 掷一个D6。掷出1-3：队伍中的每个成员失去2点生命值。掷出4-6：队伍丢弃1个战利品。为今天抽取另一个遭遇卡，并将这张卡重新洗入你的遭遇卡组。
    rewards:
  - description: 够了！我们在这里结束这一切！
    action: BQ：反派点数。1-2人队伍：在BQ底部添加一个5点反派。3-4人队伍：在BQ底部添加一个20点反派。当这个反派进入战斗垫时，增加3点初始生命值。
    rewards: 每个Gearlock获得2个技能点。每个Gearlock抽取1个宝藏战利品。获取额外2点进度点。
remark:
progress: [0,2]