title: 莫尔诺尔商人
story: 莫尔诺尔商人是一群难缠的家伙，总是在对他们来说最合适的时机出现。尽管他们在提供服务时要求提前全额付款，但他们也会随机出现，毫无理由地要求额外的钱或战利品。不幸的是，他们掌握着重要筹码，知道保守这次冒险对Ebon的秘密有多重要。这些愚蠢的游戏令人疲惫不堪。他们又来了，要求参加明显对他们有利的比赛！
choices:
  - description: 另一个挑战。这将浪费宝贵的时间！
    action: 每个Gearlock必须参加他们自己的危险飞镖挑战。胜利：Gearlock可以抽取2个战利品。失败：Gearlock必须丢弃1个战利品（如果有的话）。将这次遭遇重新洗入你的遭遇卡组。
    rewards: 胜利：Gearlock可以抽取2个战利品。失败：Gearloc必须丢弃1个战利品（如果有的话）。
  - description: 不再玩游戏！现在停止！嗯……是不是太草率了？他们看起来很生气！
    action: BQ：反派点数。战斗开始时，每个Gearlock受到等同于队伍人数的伤害。如果战斗失败，将这次遭遇重新洗入你的遭遇卡组。
    rewards: 每个Gearlock获得2个技能点。获取额外1点进度点。每个Gearlock抽取1个战利品。
remark:
progress: [0,1]
card_type: special