title: 艰难出门
story: 刚走了15步……15步！就有一支箭射穿了一个Gearloc的靴子。幸运的是，没有伤到脚趾。牙关紧咬，疼痛地扯出箭，同时四处张望，满脸窘迫。哎哟！！！现在，怒气冲天，是时候还击那些在树林边缘的阴影人物了。一阵骚动在城墙上爆发，打断了所有的思绪。守卫们已经发现了这些大胆的入侵者，并开始搭箭准备射击。他们的帮助随时准备就绪。不管喜不喜欢，这场冒险已经开始了！
choices:
  - description: 呼叫守卫帮忙。
    action: BQ：反派点数。每回合开始时，城墙上的箭对每个反派造成1点真实伤害。推荐给第一次冒险者。
    rewards: 每个Gearlock获得1个技能点。每个Gearlock抽取1个战利品。
  - description: 是时候让奥本达看看Gearloc的实力了。在奥本达的注视下，你感受到一股额外的肾上腺素，准备进行一场无援战斗。
    action: BQ：反派点数。
    rewards: 每个Gearlock获得2个技能点。每个Gearlock抽取1个战利品。
remark: 如果战斗失败，将这次遭遇放回遭遇卡组顶部。
progress: 1