title: 深陷机械残骸
story: 我们一生中见过无数不同的机器人，但这些被丢弃的零部件和碎片却有所不同。像是Tink的商店里常见的大型金属齿轮、板子和链轮在这里都看不到了。这些零部件更加精密，几乎模仿了有机生物的解剖结构。肌腱被复杂的电线所取代。这里已经进行了一场战斗，而这些零件和武器看起来很有用。遗憾的是，它们对接近的敌人也同样有用。
choices:
  - description: 挑选一堆机械废料。
    action: BQ：反派点数。加3点。将8个攻击骰和8个防御骰放置在所有16个战斗垫位置上，每个位置放置一个骰子，按你选择的任意排列方式。当一个单位占据一个带有骰子的位置时，它将获得该骰子，与其其他骰子一起使用（不消耗Dex）。一旦骰子被掷出并应用后，从战斗垫上移除。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 我们不该花点时间检查一下吗？
    action: BQ：反派点数。不偷看，将反派面朝下放置在战斗垫上的反派远程位置（Init Die放在Init Meter底部）。反派在被攻击或每回合开始时才会被翻转（翻转反派，获得HP并使用属性）。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general