title: 山中的谜团
story: 这很有趣。经过了许多天，这是我们第一次发现一个开凿在山中的矿井。从外观看，这些隧道必定深入内部。“也许这是一个秘密通道，”有人插话道。“或者它通向一个辉煌的宝库，”另一个人补充道。我自己不会感到惊讶，如果它是一个虐待狂龙的烤箱的入口，那我们就是主菜。不管怎样，守卫入口的哨兵是个严重的威胁，但他们手中稀有而华丽的雕刻武器令人着迷且非常诱人。值得冒这个险吗？
choices:
  - description: 让我们看看这个兔子洞有多深...
    action: BQ：反派点数。队伍中每一个Gearloc增加1个5点数的反派至BQ底部。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。每个Gearloc可以抽取1个宝藏战利品。获取2点进度点。
  - description: 跟着哨兵。这已经是一场大战了。
    action: BQ：反派点数。增加6个反派点数至BQ。队伍中每一个Gearloc增加1个1点数的反派至BQ底部。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取2点进度点。
  - description: 让我们侦察并返回。
    action: 翻开你活动堆栈中的2个反派（可以移至底部）。将此遭遇卡放回遭遇牌堆顶端。此选择没有遭遇奖励。
    rewards:
remark:
progress: [2,2,0]
card_type: general