title: 大胆挑战
story: 尽管午后的阳光遮掩了他的面貌，但前方那位陌生人的巨大身影让我们的背脊感到一阵寒意。每个人都能感受到这一点。事实是，他...就那样站在那儿，方方正正地挡住了我们唯一的前进道路，使得对抗成为了一种痛苦的必然。然而，看起来我们中大多数人今天可能还会避免这种不受欢迎的锻炼，因为这个高大的身影有他自己的计划。当他的声音在我们之间的间隙中雷鸣般地回响时，一个挑战变得明朗起来，他宣称：“选择你的勇士，然后去死吧！”
choices:
  - description: 你好，巨人...
    action: BQ：反派点数。从反派BQ顶部在通道1中放置1个反派。选择1个Gearloc与其对抗3回合。如果反派或Gearloc被早早击败，剩余的反派和Gearloc将在当前回合结束时加入战斗。否则，他们将在第3回合结束时加入战斗。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 无视他的挑战！我们来对付他！
    action: BQ：反派点数。1-2人的队伍： 增加4点反派分数。3-4人的队伍： 增加8点反派分数。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general