title: 地面不稳
story: 没有什么比经历一天艰难的砍杀后，在烟雾缭绕的篝火旁享用一顿热腾腾的饭菜，或者喝一瓶Patches的兴奋剂，或者Tantrum自制的麦酒更令人满足的了。能够在一起，保持所有的四肢依然完好无损，并且继续前行，这感觉真好。不过，有点奇怪的是，似乎我们在篝火旁躺的时间越长，一切变得越高大。等一下！我们的装备去哪了？大地正在吞噬我们的锅碗瓢盆！一切都在我们眼前消失…流沙！
choices:
  - description: 把这些绳子绑在箭上！找到一棵树然后放飞它们！
    action: 在每个反派远程位置放置一个防御骰（树目标）。在每个Gearloc远程位置放置一个攻击骰（箭）。选择一个Gearloc将每个攻击骰弹中到防御骰（同一个lane，而却不能将其从垫子上击落）。至少3个树目标必须被箭击中才算成功。
    rewards: 每个Gearlock获得1个技能点。获取1点进度点。
  - description: 莫尔诺尔的援助…最昂贵的那种。我们接受。
    action: 我们自由了！但是作为交换，我们被迫玩危险飞镖…为什么他们那么喜欢这个游戏？每个Gearloc都必须参加一次危险飞镖挑战。至少有一个Gearloc获胜，团队才能取得胜利。将特殊特殊遭遇-莫尔诺尔商人洗入牌堆。
    rewards: 每个获胜者还会获得1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general