title: 恐惧之沼
story: 谁说这个沼泽是捷径，那人聪明得保持了沉默！我们整整一天半夜都在淤泥中跋涉，泥浆已经没过我们的喉咙，队伍的士气正在迅速下降。我正说服自己发声，这时前方突然传来的“呱呱”声打断了我的思绪。我们在进来的时候避开了类似的声音，但现在看来我们别无选择，只能面对这个沼泽里的生物。不然就只能在寻找出口的途中因臭味昏倒。
choices:
  - description: 沼泽生物的死期到了！
    action: BQ：反派点数。1-2人队伍：增加3个反派点数。3-4人队伍：增加6个反派点数。使用尽可能多的沼泽类型反派创建反派队列（来自活动、已击败或非活动堆叠）。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取2点进度点。
  - description: 这臭味正在渗透到我身上……不，真的是在我身上！
    action: BQ：反派点数。每个Gearloc都必须通过健康检查才能留在沼泽中。任何未通过检查的Gearloc都必须在战斗开始时带有毒素2效果骰。健康检查：掷一个D6。如果当前生命值大于D6结果，则通过。如果不大于，则未通过检查（不影响遭遇成功）。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [2,1]
card_type: general