title: 到底是要拼一把还是回家
story: 所以有两队反派来了，是吧？好吧，我们不能冒险同时与他们作战，那么我们该选择哪一队呢？我们可能会被打得很惨，但第一队显然更强大，因此我们有更好的机会获得更好的战利品。而且，如果我们要挨打，我们最好得到一些闪闪发光的东西。话虽如此，我记得《Gearloc 异想录》中有一句话提到“把敌人踩在地上”的重要性，而我们显然需要一个明确的结果来使局势对我们有利。
choices:
  - description: 那么这是“我们就是沙袋”的计划……真的吗？
    action: BQ：反派点数。1-2 人小队：在 BQ 顶部添加一个 5 点反派。3-4 人小队：在 BQ 顶部添加两个 5 点反派。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取2个战利品。获取1点进度点。
  - description: 希望我的反派击败之靴仍然合脚！
    action: BQ：反派点数。减少 2 个反派点数。
    rewards: 每个Gearlock获得1个技能点。队伍可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general