title: 失而复得
story: “这下好了，我们迷路了！”一群森林出身的家伙怎么会在树林里迷路呢？幸运的是，我们听到一位慈祥的老奶奶坐在附近的石头上喊道：“迷路了吗？也许我可以帮忙。”我们围着那位好奇的老奶奶，她向我们提出了一项交易：“用一些对你们来说有价值的东西来换取我这神秘的指南针。它只会指示持有者最想去的方向。”
choices:
  - description: 当然，还有什么更糟的事情可能发生呢？
    action: 队伍每给老太太一个战利品，你的队伍可以掷一个D6（最多4次）。1人队伍：每个战利品算作2个。掷骰子。总计你的骰子点数。
    rewards: 0点：没有进度。1-6：每个Gearlock获得1个技能点。获取1点进度点。7-12：每个Gearlock获得2个技能点。获取1点进度点。13-18：每个Gearlock获得2个技能点。队伍获取1个宝藏战利品。获取1点进度点。19+：每个Gearlock获得2个技能点。每个Gearlock获取1个宝藏战利品。获取1点进度点。
remark:
progress: [1]
card_type: general