title: 白骨之床
story: “在这边，”我们的侦察兵喊道，我们一天都在追踪的那组奇怪的足迹，我们希望这些足迹能带我们找到一些特别的东西。好吧……它们确实带我们找到了东西。不幸的是，它们把我们带到了一个洞穴，洞穴里堆满了破碎的盔甲和被啃咬过的骨头，那些骨头曾经是其他过于急切的倒霉蛋……我是说冒险者。更令人不安的是，有双锐利的眼睛透过黑暗盯着我们——这里有某种活物和我们在一起……
choices:
  - description: 四散而逃！
    action: BQ：反派点数。将一个20点反派放到BQ顶部。在整个队伍中，选择1-6个攻击和防御骰子在这场战斗中消耗（不能使用）。Gearloc必须至少有这么多的攻击和防御骰子。在每轮开始时掷一个D6。如果它小于或等于消耗的队伍骰子数，在这一轮将一个眩晕效果骰放在那个20点反派上。如果胜利，将特别遭遇——狩猎猎人洗入你的遭遇牌堆（如果还没有的话）。
    rewards: 每个Gearlock获得3个技能点。每个Gearloc可以抽取1个宝藏战利品。获取1点进度点。
  - description: 逃跑！！！
    action: BQ：反派点数。每个Gearloc在战斗开始前受到2点伤害。
    rewards: 每个Gearlock获得2个技能点。获取1点进度点。
remark:
progress: [1,1]
card_type: general