title: 臭味
story: 太好了，前方出现了岔路——又有新的争论话题了。无论如何，我们的道路现在分岔了。左边，空气中弥漫着死亡的气息——这是一片有毒沼泽的标志。右边，道路安静而平和地延伸——在这些土地上，这从不是个好兆头。像往常一样，我们的决定和前方的道路一样不确定。
choices:
  - description: 让我们迎战沼泽吧！我们有抗辐射药？……没有？动力装甲呢？
    action: BQ：反派点数。在战斗中，每个Gearlock的敏捷上限为3。每回合开始时掷一个D6。若结果为1-3，所有Gearloc立即受到1点真实伤害。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 否决沼泽，选择“诡异安静的道路”。
    action: BQ：反派点数。每个Gearloc可以在战斗开始前掷他们的防御骰子（掷到骨头不能使用）。在战斗中，远程敌人+1攻击骰。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general