title: 小心……前方爆炸！
story: 我们整整一天都在奋力前行，终于到达了岩石峭壁。这是一个具有战略优势的位置。从这里可以眺望山谷和河流区域，也是一个寻找夜晚小洞穴的好地方。但命运似乎总不眷顾Gearloc。我们的前方是巨大的落石滑坡，夜幕降临前我们无法绕过去，而身后是一群我们不愿再次惊动的兽人和狼群。这是一个充满火药味的局面……或者说，很快就会是！
choices:
  - description: 让我们开始爆破吧！
    action: 你的队伍中每个Gearloc，放置2堆3点生命值以表示瓦砾在任何反派位置上（每个位置一堆）。将Gearlocs放置在远程位置，他们在那里保持安全距离。每个Gearloc有2个投掷炸药。投掷炸药：瞄准任何位置，每个投掷炸药投掷2个攻击骰子。对目标造成伤害，并对所有相邻位置造成一半伤害（向下取整）。队伍必须使用他们拥有的炸药（任何回合顺序，一次性可以使用任意数量的炸药）清除所有瓦砾（HP）才能成功。
    rewards: 每个Gearlock获得2个技能点。
remark:
progress: [1]
card_type: general