title: 终于，开阔的天空！
story: “啊，终于有阳光和新鲜空气了！我都快忘了地平线是什么样子了，”有人欢呼着，我们开心地走出了茂密森林的重压。正午的阳光使我们的精神比几天来都高涨了一些——直到空中响起了战斗的警报。我们的第一反应是跑去躲避，但这可能会让我们背上中箭。
choices:
  - description: 我们就在这里战斗！
    action: BQ：反派点数。你的队伍在战斗中不能使用防御骰。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 进入森林！
    action: 在战斗的前两回合中，你的队伍不能掷任何除防御骰以外的骰子。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general