title: 目标可能看起来更远...
story: “快进来躲躲，”我们的侦察员说，我们立刻冲进了一个洞穴，那里能够很好地躲避倾盆大雨。当我们拧干浑身湿透的衣服时，我们意识到狭窄的入口通向了一个巨大的洞穴。我们被一些来源不明的尘土飞扬的桶包围。洞穴顶部有一个开口，似乎捕捉到了暴风雨中唯一的一缕阳光。突然，在这些桶的中央，一只带有精美锁头的大箱子被上方聚焦的光束揭示出来。精美的锁头反射出光线，让我们难以直视，但我们也无法移开目光……
choices:
  - description: 尝试打开它！
    action: 抽取最上面的宝藏战利品卡。选择一个Gearlock进行开锁尝试。如果他们能解开所有3个锁，这个Gearlock将获得解锁的宝藏战利品。如果不成功，丢弃战利品。无论结果如何，都会完成遭遇。
    rewards: 每个Gearlock获得1个技能点。可能获取宝藏战利品。获取1点进度点。
  - description: 检查这些桶！
    action: 选择1-4个桶进行破坏。为每个桶的HP（强度）掷一个D6，并按从强到弱的顺序放在战斗垫上。每个Gearlock轮流掷出总攻击骰来按照相同顺序破坏桶。每个Gearlock只能攻击一个桶。破坏的总桶数等于获得的战利品总数。
    rewards: 每个Gearlock获得1个技能点。可能获取战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general