title: 熄灯行动
story: “所有人保持安静，”随着火炬熄灭，命令响起，我们全都聚拢在一起。“那群劫匪就是几天前偷走我们装备的人。这是我们的机会，但不能战斗。看到他们营地周围的灯笼了吗？那就是我们的目标。在他们睡觉时摧毁它们，然后抓起我们的东西，在灌木丛的另一边汇合。如果你不能射中灯，希望我们中的一个人能补上。现在出发… 祝你好运！”
choices:
  - description: 熄灭灯笼！
    action: 每个Gearlock掷反派Init Die来代表一个灯笼以及它与队伍的“距离”。每个Gearlock选择一个灯笼。使用他们自己的Init Die，Gearlock必须掷出大于或等于灯笼的数字来熄灭它。无论结果如何，遭遇成功。
    rewards: 每个Gearlock获得1个技能点。每熄灭一个灯笼，队伍获得1个战利品。获取1点进度点。
remark:
progress: [1]
card_type: general