title: 路中的树桩
story: 嗯，一个大而中空的树桩竟然正好坐落在这条原本荒芜的小径中间？如果这还不够奇怪的话，有人还在它的中心堆满了诱人的宝石和物品。这无疑引起了我们的注意，但一切都显得不对劲。那些物品放置在上面的齿轮触发板，以及从树桩深处延伸到树林中的细线，都证实了这个想法。然而……只要有一点运气和灵巧的双手……
choices:
  - description: 迅速拿走！
    action: BQ：反派点数。队伍选择一个1到6的数字。掷一个D6骰子。如果你掷出的数字高于你选择的数字，抽取与你选择的数字相等的战利品。如果你掷出的数字等于或低于你选择的数字，将你选择的数字加到反派点数总和中。
    rewards: 每个Gearlock获得2个技能点。队伍获得？个战利品。获取1点进度点。
remark:
progress: [1]
card_type: general