title: 急需食物！
story: 我们已经厌倦了在这片森林里寻找任何能找到的食物。这里的“食物”似乎铁了心要毒死我们。在运气好的日子里，我们能抓到并吃掉那些试图从我们的火堆里偷走温暖的小动物。在战斗中，我们的力量只取决于我们最后一餐的食物。我们需要尽快填饱肚子，免得有人吃了不该吃的东西。我们应该利用下午时间少关注敌人，多关注我们的肚子。
choices:
  - description: 我们猎杀小动物！
    action: 将Gearlock放在战斗垫上。用1点生命值的小动物填满所有剩余的位置。Gearlock和小动物轮流行动（小动物先行动）。小动物：掷一个D6。找到匹配的路线（5号算作1号路线，6号算作2号路线）。如果有小动物在那条路线，每个小动物必须同时将其生命值移到相邻的另一个小动物上（如果没有相邻的，移除该小动物）。如果该路线没有小动物，移除垫上最小HP的小动物。Gearlock：追捕并击败小动物，只能使用攻击骰子（和敏捷）。小动物只能在一次尝试中被击败。如果击败，将小动物的生命值放在戴洛克准备区域。如果尝试失败，从垫上移除小动物。它逃走了！ 继续直到所有小动物都消失。Gearlock收集的任何生命值都会保留在准备区，作为你下一次战斗的Buff HP。
    rewards: 每个Gearlock获得1个技能点。获取1点进度点。
remark:
progress: [1]
card_type: general