title: 排列整齐的鸭子
story: 荒地吸引着各种各样的隐士、怪人、亡命之徒和非法企业家。遇到一个摇摇欲坠的家园，谁也猜不透会发现什么。如果有机会在接下来的战斗中获得优势，那么，谁能说这不会是一个高尚或有用的支线任务呢？前方的小屋看起来我们发现了这样的机会。从远处看，它似乎是一个无害的农场，但我们Gearlocs知道，永远不要相信第一印象……尤其是在这么远的北方。
choices:
  - description: 帮助需要帮助的农夫！杀死那些老鼠！
    action: 一个不是很“史诗”的任务，但没有一个清理地下室老鼠的任务故事就不完整。你必须面对的老鼠数量是你的队伍大小+1。为每只老鼠投掷一个D6来决定它的HP。在战斗垫的近战位置1-4放置HP堆栈，然后是远程位置。老鼠不会移动、攻击或采取行动。将Gearlocs放置在它们的起始位置。队伍现在有1轮时间尽可能多地对老鼠造成伤害。将这视为正常战斗。如果你的队伍击败了所有老鼠（除一只外），你就成功了。
    rewards: 如果你成功杀死了所有老鼠，农夫会非常高兴，并给你一张破旧的地图。将特殊遭遇——“乌晶门”洗入你的遭遇牌组。每个Gearlock获得1个技能点。获取1点进度点。
remark:
progress: [1]
card_type: general