title: 分散的太开了
story: 左右都是掠夺者……不，是一群可怜的商队在山谷底部沿着远处的河道前行。“让我们去抓他们！”有人喊道。但抓谁呢？已经在山谷尽头、即将超越商队的掠夺者？还是那群沿着更远路线行进、危险地靠近我们的掠夺者？
choices:
  - description: 我们不能同时救他们！为更大的一群怪物设陷阱！
    action: BQ：反派点数。1-2人的队伍：在反派队列顶部添加两个1点反派。3-4人的队伍：在反派队列顶部添加两个5点反派。每个反派在进入战斗垫时失去2点生命值。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 全抓住！吹响号角！
    action: BQ：反派点数。1-2人的队伍：在反派队列顶部添加两个1点和一个5点反派。3-4人的队伍：在反派队列顶部添加三个5点反派。如果成功，可以选择所有恢复阶段选项（而不仅仅是一个）。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。每个Gearloc可以抽取1个宝藏战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general