title: 洞穴还是蛋糕？
story: “大家都过来！”经过几个小时的侦察，我们似乎有几个不错的选择可以考虑，并可以在黄昏的掩护下实施。我们可以冒险进入狭窄的空间，探索北边的洞穴，那里似乎有丰厚的战利品，或者稍事休息，可能还能从东边山脊上打盹的掠夺者那里弄到一顿不错的饭。 “有人怕蝙蝠的吗？”
choices:
  - description: 哇，好闪亮！我们来干吧！
    action: BQ：反派点数。队伍人数 1-2：增加 6 反派点数。队伍人数 3-4：增加 12 反派点数。
    rewards: 每个Gearlock获得2个技能点。队伍获取2个宝藏战利品。获取1点进度点。
  - description: 永远不要拒绝蛋糕！
    action: BQ：反派点数。队伍有先发制人。
    rewards: 每个Gearlock获得2个技能点。获取1点进度点。
remark:
progress: [1,1]
card_type: general