title: 这是陷阱！
story: 感觉不对劲，我们本能地停下脚步。仔细观察，我明白了原因：我们脚下的叶子颜色和形状与头顶的叶子不符。我的警告来得太迟，有人愚蠢地又迈出了一步。“咔哒”威胁声响起，大家都再次僵住了。“不要动，”一个声音警告道，“有人踩在陷阱上，准备爆炸了！”很明显，我们队伍中有“显而易见队长”……
choices:
  - description: 快找出来并拆除！
    action: BQ：反派点数。反派在这次战斗中拥有先发制人。选择一个Gearloc尝试解锁4L - 3T爆炸装置。如果失败，队伍必须选择另一个选择，并且反派仍然拥有先发制人。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。
  - description: 小心！陷阱就是陷阱！
    action: BQ：反派点数。掷一个D6。如果某Gearloc的HP与骰子结果最接，那么他在战斗开始前失去3点生命值（队伍选择平局情况）。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。
remark:
progress: [1,1]
card_type: general