title: 自由贸易往往并不自由
story: 在长时间没有重大收获之后，一群靠近的商人是一道欢迎的风景。他们看起来很友好，并迅速招呼我们进行交易。我猜我们应该更谨慎一些，因为当我们被四个戴着兜帽的身影包围时，我们完全措手不及。“也许这是他们迎接每个人的方式？”我们中的一个人建议道。“或者我们已经死了，”我回答道。无论如何，我们需要快速行动！
choices:
  - description: 贿赂莫尔诺尔！
    action: 队伍必须放弃相当于队伍大小的战利品。莫尔诺尔一言不发地离开。将特殊遭遇-莫尔诺尔商人洗入你的遭遇牌组中，如果尚未在其中。
    rewards: 每个Gearlock获得2个技能点。获取1点进度点。
  - description: 这是测试吗？旋风！
    action: 选择1个Gearloc。你有5轮时间击败4个披着斗篷的人。将4堆HP（3HP、5HP、4HP、4HP）放置在敌人近战位置上，顺序任意。这些披着斗篷的人不移动也不攻击。所选的Gearloc将其视为正常战斗（确实影响遭遇成功）。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general