title: 天火
story: 一阵微风吹过营地，空气中弥漫着一丝硫磺的气味。随着下一阵风，显然有什么东西着火了，而且似乎是我们！“该死的怪物！”有人喊道，紧接着是一阵Gearlocs慌乱地拍打被烧焦的头发，并躲避燃烧的树枝的声音。火花如雨点般落在我们身上，我们疯狂地寻找掩护，因为我们知道有条龙正在瞄准我们。我们的选择有限，因为其他不速之客也正涌入空地。我们必须尽快采取行动，否则我们就完了！
choices:
  - description: 龙来了！我们反击！
    action: BQ：反派点数。第一回合，仅远程Gearlocs行动（跳过所有反派和其他Gearlocs）。1-2人队伍：将一个5点龙反派添加到BQ顶端。3-4人队伍：将一个20点龙反派添加到BQ顶端。如果消灭了一个20点龙，将特殊遭遇——狩猎猎人洗入遭遇卡组中（如果还未加入）。
    rewards: 每个Gearlock获得3个技能点。每个Gearloc可以抽取1个战利品。
  - description: 低下头！在地面上战斗！
    action: 战斗期间，火焰从天而降，每回合开始时对所有Gearlocs造成1点真实伤害。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。
remark:
progress: [1,1]