title: 如同待宰的猪
story: 整整一天，我们仿佛被引导到一条特定的路径上。从不可通行的路障到旅行商人提供的奇怪“建议”，这一切绝不是巧合。如果还会有什么事情发生，那就是它！另一个奇怪的现象！什么时候在无人探勘的森林里竖起了路标？这个路标还是匆匆制作的，油漆还很新。上面写着：向左是乐趣，向右是厄运。
choices:
  - description: 当然是乐趣！
    action: BQ：反派点数。在设置和战斗期间，每当一个有5点或更多HP的反派进入战斗垫时，立即在反派队列的底部添加1个1点反派。
    rewards: 每个Gearlock获得3个技能点。每个Gearlock可以抽取1个战利品。获取1点进度点。
  - description: 揭穿他们的谎言。
    action: BQ：反派点数。原来“厄运”其实是一个无人守卫的复杂锁的战利品箱。在你的跟踪者意识到你选择的路线之前，你有一次机会。抽取顶部的宝藏战利品箱卡。选择1个Gearlock进行一次开锁尝试。如果成功，那个Gearlock立即获得并解锁战利品箱卡。如果不成功，丢弃它（不影响遭遇成功）。
    rewards: 每个Gearlock获得1个技能点。每个Gearlock可以抽取1个战利品。获取1点进度点。可能会获取一个宝藏战利品。
remark:
progress: [1,1]
card_type: general