title: 有亮晶晶的东西来了
story: 隐藏在一小片树丛中，让我们的队伍能够在黄昏时欣赏荒野的景色，但我们的短暂休憩被打断了，当有人注意到两个身影携带的灯笼的摇曳光芒，正朝着西北方大约一百箭之遥的一大团火光走去。不幸的是，Gearlocs很容易被明亮闪耀的东西分散注意力，所以我们又一次行动了起来…
choices:
  - description: 跟随并伏击
    action: 抽取两个5点反派。你的队伍现在就与他们战斗。如果你成功了，你必须用当前的HP再战斗一次（重置战斗和Gearloc垫板）。BQ：反派点数（并从你的总点数中减去8点）。如果你输掉任何一场战斗，你将不会获得任何进展或奖励。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
  - description: 坚持！我们在黄昏时全力攻击他们！
    action: BQ：反派点数。掷两次D6。将结果相加，并将该数字加到你的反派点数总数中。队伍获得先发制人。
    rewards: 每个Gearlock获得3个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general