title: 刺猬般的遭遇
story: 遇到一个地精侦察兵总是一个好日子——一个已经腐烂在地上的地精侦察兵也是如此。遇到一只凶猛的巨狼也是一样的好日子。然而，当你发现一个地精尸体被夹在一只巨狼的下巴里，而那只巨狼也已经死了，这可能是一个问题。“哦，沼泽怪的胆汁，”有人摇着头说。不奇怪的是，狼的脖子里还插着三把匕首，而狼皮仍然是温暖的。侦察兵的包里有一张粗糙的地图，标记着附近一个充满荆棘的灌木丛，隐藏的道路不再隐藏，还标记了一个金色宝箱的位置。显然，我们不是第一个到这里探险的人。
choices:
  - description: 这是张藏宝图！这根本不是选择！
    action: BQ：反派点数。将一个20点的反派加到战斗序列的顶部。
    rewards: 每个Gearlock获得3个技能点。每个Gearloc可以抽取1个战利品。每个Gearloc可以抽取1个宝藏战利品。获取2点进度点。
  - description: 放火烧了这灌木丛！攻击所有出来的东西！
    action: BQ：反派点数。将一个20点的反派加到战斗序列的顶部。每回合结束时，战斗垫上的所有反派受到2点真实伤害。
    rewards: 每个Gearlock获得3个技能点。每个Gearlock可以抽取1个战利品。获取2点进度点。
remark:
progress: [2,2]
card_type: general