title: 泥巴从来没杀过人，对吧？
story: 我有幽闭恐惧症，你们都讨厌弄脏；这真是个大烂摊子。没错，通往东北方向的小山路要快得多，但看看那条路有多窄！我们肯定会遇到阻碍并被夹在中间！我宁愿弄脏裤子，走向西边不可避免的泥潭；看看那条路有多开阔。而且，你们这些家伙也可以用免费的面膜来改善那些红润的脸色！那么我们该怎么办呢？时间不多了！
choices:
  - description: 排成一列前进！谁是我们的队伍领头？
    action: BQ：反派点数。战斗限制在第一列。进入战斗区的单位总是先占据近战位置（如果有空），然后是远程位置。当单位被击败时，剩余的单位将立即移动到近战位置（如果有空）。不允许移动。
    rewards: 每个Gearlock获得1个技能点。每个Gearloc可以抽取1个战利品。获取2点进度点。
  - description: 让我们去角质吧！好吧，也许我忘了我们Gearloc比大多数Ebon小一点——这是个小疏忽！
    action: BQ：反派点数。每个Gearloc在战斗中减少1点敏捷。此外，在移动之前，你必须掷一个D6骰子。如果掷到1-3，你会被困住，无法在本回合移动。
    rewards: 每个Gearlock获得2个技能点。每个Gearloc可以抽取1个战利品。获取1点进度点。
remark:
progress: [1,1]
card_type: general